on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/xcodebuild@v1
      with:
        swift: ~5.5
        warnings-as-errors: true
  linux:
    runs-on: ubuntu-latest
    container:
      image: swiftlang/swift:nightly-5.5
    steps:
    - uses: actions/checkout@v2
    - run: swift test --parallel -Xswiftc -warnings-as-errors
